services:
  postgres:
    image: postgres:17-bullseye
    container_name: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project_network

  redis:
    image: redis:8
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: ["sh", "-c", "redis-server --requirepass $REDIS_PASSWORD"]
    volumes:
      - redis_data:/data
    networks:
      - project_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgres
      - redis
    networks:
      - project_network

networks:
  project_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
